### PR TITLE
add device timezone to recordings table

### PR DESCRIPTION
**Pull request by Mebareksaf**

### CODE REVIEW

**Comment by gBillal** [comment]
@halimb do you have a better way of showing the timezone on the recordings tab ?? i don't like showing the timezone in the table since the value won't change/not used for filtering/not used for sorting

**Comment by halimb** [comment]
@gBillal do you mean not storing it at all? or storing it in a different table?

If it's about not storing it at all, I don't see another way to get the information.
Even though timestamps in ISO 8601 format can help induce the timezone, it's not perfect.

I think it's needed for:
- Accounting for DST changes
- Scheduling future operations (DST again)
- Accounting for potential changes in the timezone definition itself (+DST) (example: some [active proposals in the EU](https://www.europarl.europa.eu/RegData/etudes/BRIE/2018/630308/EPRS_BRI(2018)630308_EN.pdf) are trying to change the timezone definitions of some or all EU countries).

PS: sorry for the late response.

**Comment by gBillal** [comment]
@halimb the question is purely front-end. Currently we show the date time in the recordings tab in the device/camera timezone. And the user who look at the recordings won't know in which timezone.
Do you think that showing the timezone in the table as a column is good (since the value is the same for all the recordings) ?
Or showing the timezone formatted on the datetime `2024-50-25 06:02 CST` or `2024-50-25 06:02 -0600` ?
Or any other suggestion ?

**Comment by halimb** [comment]
oh, I misunderstood.
Yes, I think the timestamp + offset  is good enough, no need for a new column IMO

**Comment by gBillal** [comment]
@halimb ok I think it's the same for me. Which version is better, the name of the zone or the offset ?
@Mebareksaf update your PR to include the time zone in the (stat date and end date)

**Comment by gBillal** [comment]
Closing in favor of https://github.com/evercam/ex_nvr/pull/389

**Pull request closed without merging**
